const { Markup } = require("telegraf");
var langs = {
  'auto': 'Automatic',
  'af': 'Afrikaans',
  'sq': 'Albanian',
  'am': 'Amharic',
  'ar': 'Arabic',
  'hy': 'Armenian',
  'az': 'Azerbaijani',
  'eu': 'Basque',
  'be': 'Belarusian',
  'bn': 'Bengali',
  'bs': 'Bosnian',
  'bg': 'Bulgarian',
  'ca': 'Catalan',
  'ceb': 'Cebuano',
  'ny': 'Chichewa',
  'zh-CN': 'Chinese (Simplified)',
  'zh-TW': 'Chinese (Traditional)',
  'co': 'Corsican',
  'hr': 'Croatian',
  'cs': 'Czech',
  'da': 'Danish',
  'nl': 'Dutch',
  'en': 'English',
  'eo': 'Esperanto',
  'et': 'Estonian',
  'tl': 'Filipino',
  'fi': 'Finnish',
  'fr': 'French',
  'fy': 'Frisian',
  'gl': 'Galician',
  'ka': 'Georgian',
  'de': 'German',
  'el': 'Greek',
  'gu': 'Gujarati',
  'ht': 'Haitian Creole',
  'ha': 'Hausa',
  'haw': 'Hawaiian',
  'he': 'Hebrew',
  'iw': 'Hebrew',
  'hi': 'Hindi',
  'hmn': 'Hmong',
  'hu': 'Hungarian',
  'is': 'Icelandic',
  'ig': 'Igbo',
  'id': 'Indonesian',
  'ga': 'Irish',
  'it': 'Italian',
  'ja': 'Japanese',
  'jw': 'Javanese',
  'kn': 'Kannada',
  'kk': 'Kazakh',
  'km': 'Khmer',
  'ko': 'Korean',
  'ku': 'Kurdish (Kurmanji)',
  'ky': 'Kyrgyz',
  'lo': 'Lao',
  'la': 'Latin',
  'lv': 'Latvian',
  'lt': 'Lithuanian',
  'lb': 'Luxembourgish',
  'mk': 'Macedonian',
  'mg': 'Malagasy',
  'ms': 'Malay',
  'ml': 'Malayalam',
  'mt': 'Maltese',
  'mi': 'Maori',
  'mr': 'Marathi',
  'mn': 'Mongolian',
  'my': 'Myanmar (Burmese)',
  'ne': 'Nepali',
  'no': 'Norwegian',
  'ps': 'Pashto',
  'fa': 'Persian',
  'pl': 'Polish',
  'pt': 'Portuguese',
  'pa': 'Punjabi',
  'ro': 'Romanian',
  'ru': 'Russian',
  'sm': 'Samoan',
  'gd': 'Scots Gaelic',
  'sr': 'Serbian',
  'st': 'Sesotho',
  'sn': 'Shona',
  'sd': 'Sindhi',
  'si': 'Sinhala',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'so': 'Somali',
  'es': 'Spanish',
  'su': 'Sundanese',
  'sw': 'Swahili',
  'sv': 'Swedish',
  'tg': 'Tajik',
  'ta': 'Tamil',
  'te': 'Telugu',
  'th': 'Thai',
  'tr': 'Turkish',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'uz': 'Uzbek',
  'vi': 'Vietnamese',
  'cy': 'Welsh',
  'xh': 'Xhosa',
  'yi': 'Yiddish',
  'yo': 'Yoruba',
  'zu': 'Zulu'
}

let inlB = Markup.button.callback;
let inlK = Markup.inlineKeyboard;
const kB = {
  eng: ["🏴󠁧󠁢󠁥󠁮󠁧󠁿 English", "en"],
  uzb: ["🇺🇿 Uzbek", "uz"],
  turk: ["🇹🇷 Turkish", "tr"],
  arab: ["🇸🇦 Arabic", "ar"],
  kazak: ["🇰🇿 Kazakh", "kk"],
  china: ["🇨🇳 Xitoy", "zh-TW"],
  russ: ["🇷🇺 Russian", "ru"],
  korea: ["🇰🇷 Korean", "ko"],
  portugal: ["🇵🇹 Portugal", "pt"],
  german: ["🇩🇪 German", "de"],
  frans: ["🇫🇷 French", "fr"],
  usa: ["🇺🇸 USA", "en"],
  hindi: ["🇮🇳 India", "hi"],
  italian: ["🇮🇹 Italian", "it"],
  japan: ["🇯🇵 Japan", "ja"],
  ukrain: ["🇺🇦 Ukrain", "uk"],
  back: ["🔙 ortga qaytish", "🔙 back"],
};
const languages = inlK([
  [inlB(kB.uzb[0], "uz"), inlB(kB.eng[0], "en")],
  [inlB(kB.turk[0], "tr"), inlB(kB.arab[0], "ar")],
  [inlB(kB.kazak[0], "kk"), inlB(kB.china[0], "zh-TW")],
  [inlB(kB.russ[0], "ru"), inlB(kB.korea[0], "ko")],
  [inlB(kB.portugal[0], "pt"), inlB(kB.german[0], "de")],
  [inlB(kB.frans[0], "fr"), inlB(kB.usa[0], "en")],
  [inlB(kB.hindi[0], "hi"), inlB(kB.italian[0], "it")],
  [inlB(kB.japan[0], "ja"), inlB(kB.ukrain[0], "uk")],
]);

const languageBreak = inlK([
  [inlB(kB.uzb[0], "uz"), inlB(kB.eng[0], "en")],
  [inlB(kB.turk[0], "tr"), inlB(kB.arab[0], "ar")],
  [inlB(kB.kazak[0], "kk"), inlB(kB.china[0], "zh-TW")],
  [inlB(kB.russ[0], "ru"), inlB(kB.korea[0], "ko")],
  [inlB(kB.portugal[0], "pt"), inlB(kB.german[0], "de")],
  [inlB(kB.frans[0], "fr"), inlB(kB.usa[0], "en")],
  [inlB(kB.hindi[0], "hi"), inlB(kB.italian[0], "it")],
  [inlB(kB.japan[0], "ja"), inlB(kB.ukrain[0], "uk")],
  [inlB(kB.back[0], kB.back[1])],
]);
module.exports = {
  languages,
  languageBreak,
  kB,
};

